_target_: src.models.StableDiffusion
pretrained_model_name: 'stable-diffusion-v1-5/stable-diffusion-v1-5'
noise_scheduler:
  _target_: diffusers.DDIMScheduler
  beta_end: 0.012
  beta_schedule: 'scaled_linear'
  beta_start: 0.00085
  clip_sample: False
  set_alpha_to_one: False
  steps_offset: 1
