test:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  num_workers: 16
  pin_memory: True
validation:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  num_workers: 16
  pin_memory: True
